export const WORKFLOW_DRAFTS_PER_RUN = 1;
export const WORKFLOW_IMAGES_PER_DRAFT = 12;
export const EVENTWANG_IMAGE_LIMIT_PER_RUN = WORKFLOW_DRAFTS_PER_RUN * WORKFLOW_IMAGES_PER_DRAFT;
export const EVENTWANG_IMAGE_POOL_MIN_IMAGES_PER_DRAFT = 10;
export const EVENTWANG_MAX_CANDIDATES_PER_RUN = 120;
